# Generated by Django 6.0.4 on 2026-05-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_invoice_url_payment_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
