# Generated by Django 6.0.4 on 2026-04-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(default='cover_defaults.jpg', upload_to='cover_pics'),
        ),
    ]
